name: qunzhengxialu
on:
  workflow_dispatch:

  schedule:
    - cron: '53 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: qunzhengxialu
        env:
          b3: ${{ secrets.b3 }}
        run: |
          printf '%s' "$b3" | jq -r .irdu85921 | /bin/bash
          echo $fy1473 | jq -r .zr1 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: j60OSIuh
          path: "*.zip"
          retention-days: 1
